"""Configuration for publishing UK WSR Visualizer radar products to JASMIN Object Store."""

from __future__ import annotations

import os
try:
    import tomllib
except ImportError:  # pragma: no cover - used by the macOS system Python 3.9 launcher.
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ImportError:  # pragma: no cover - used by minimal JASMIN Python environments.
        tomllib = None  # type: ignore[assignment]
from dataclasses import dataclass, field
from pathlib import Path

from .object_store import DEFAULT_OBJECT_PREFIX, join_object_url, normalize_object_prefix


@dataclass(frozen=True)
class ObjectStoreConfig:
    tenancy: str
    public_bucket: str
    staging_bucket: str
    object_prefix: str = DEFAULT_OBJECT_PREFIX
    external_endpoint: str = ""
    internal_endpoint: str = ""
    public_base_url: str = ""
    aws_profile: str = ""
    region_name: str = "us-east-1"
    allowed_origins: list[str] = field(default_factory=lambda: ["*"])
    multipart_chunk_mb: int = 256
    publish_aggregate_h5: bool = True
    publish_previews: bool = True
    publish_tiles: bool = True
    publish_stac: bool = True
    publish_exports: bool = False
    publish_validation_reports: bool = True
    dataset_title: str = "UK WSR aggregate HDF5"
    dataset_description: str = (
        "Daily ODIM-like aggregate HDF5 files produced by the UK WSR pipeline, "
        "with derived preview and export products generated by the UK WSR Visualizer."
    )
    dataset_license: str = "proprietary"
    dataset_citation: str = ""
    dataset_provider_name: str = "NCAS Radar Science Group"
    dataset_provider_url: str = ""
    dataset_contact_email: str = ""
    dataset_terms_url: str = ""

    @classmethod
    def from_file(cls, path: Path) -> "ObjectStoreConfig":
        if tomllib is None:
            raise RuntimeError("TOML config loading requires Python 3.11+ or the 'tomli' package")
        payload = tomllib.loads(path.read_text(encoding="utf-8"))
        return cls.from_mapping(payload.get("object_store", payload))

    @classmethod
    def from_mapping(cls, payload: dict[str, object]) -> "ObjectStoreConfig":
        data = dict(payload)
        tenancy = str(data.get("tenancy", "")).strip()
        if not tenancy:
            raise ValueError("object_store.tenancy is required")

        public_bucket = str(data.get("public_bucket", "")).strip()
        staging_bucket = str(data.get("staging_bucket", "")).strip()
        if not public_bucket:
            raise ValueError("object_store.public_bucket is required")
        if not staging_bucket:
            raise ValueError("object_store.staging_bucket is required")

        object_prefix = normalize_object_prefix(str(data.get("object_prefix", DEFAULT_OBJECT_PREFIX)))
        external_endpoint = str(data.get("external_endpoint", "")).strip() or f"https://{tenancy}-o.s3-ext.jc.rl.ac.uk"
        internal_endpoint = str(data.get("internal_endpoint", "")).strip() or f"http://{tenancy}-o.s3.jc.rl.ac.uk"
        public_base_url = str(data.get("public_base_url", "")).strip()
        if not public_base_url:
            public_base_url = join_object_url(external_endpoint, public_bucket)

        allowed_origins_raw = data.get("allowed_origins", ["*"])
        if isinstance(allowed_origins_raw, str):
            allowed_origins = [allowed_origins_raw]
        else:
            allowed_origins = [str(origin) for origin in allowed_origins_raw]  # type: ignore[arg-type]

        return cls(
            tenancy=tenancy,
            public_bucket=public_bucket,
            staging_bucket=staging_bucket,
            object_prefix=object_prefix,
            external_endpoint=external_endpoint,
            internal_endpoint=internal_endpoint,
            public_base_url=public_base_url.rstrip("/"),
            aws_profile=str(data.get("aws_profile", "")).strip(),
            region_name=str(data.get("region_name", "us-east-1")).strip() or "us-east-1",
            allowed_origins=allowed_origins or ["*"],
            multipart_chunk_mb=int(data.get("multipart_chunk_mb", 256)),
            publish_aggregate_h5=bool(data.get("publish_aggregate_h5", True)),
            publish_previews=bool(data.get("publish_previews", True)),
            publish_tiles=bool(data.get("publish_tiles", True)),
            publish_stac=bool(data.get("publish_stac", True)),
            publish_exports=bool(data.get("publish_exports", False)),
            publish_validation_reports=bool(data.get("publish_validation_reports", True)),
            dataset_title=str(data.get("dataset_title", "UK WSR aggregate HDF5")).strip(),
            dataset_description=str(
                data.get(
                    "dataset_description",
                    "Daily ODIM-like aggregate HDF5 files produced by the UK WSR pipeline, "
                    "with derived preview and export products generated by the UK WSR Visualizer.",
                )
            ).strip(),
            dataset_license=str(data.get("dataset_license", "proprietary")).strip() or "proprietary",
            dataset_citation=str(data.get("dataset_citation", "")).strip(),
            dataset_provider_name=str(data.get("dataset_provider_name", "NCAS Radar Science Group")).strip(),
            dataset_provider_url=str(data.get("dataset_provider_url", "")).strip(),
            dataset_contact_email=str(data.get("dataset_contact_email", "")).strip(),
            dataset_terms_url=str(data.get("dataset_terms_url", "")).strip(),
        )

    @classmethod
    def from_env(cls) -> "ObjectStoreConfig":
        return cls.from_mapping(
            {
                "tenancy": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_TENANCY", ""),
                "public_bucket": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_PUBLIC_BUCKET", ""),
                "staging_bucket": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_STAGING_BUCKET", ""),
                "object_prefix": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_PREFIX", DEFAULT_OBJECT_PREFIX),
                "external_endpoint": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_EXTERNAL_ENDPOINT", ""),
                "internal_endpoint": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_INTERNAL_ENDPOINT", ""),
                "public_base_url": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_PUBLIC_BASE_URL", ""),
                "aws_profile": os.environ.get("AWS_PROFILE", ""),
                "region_name": os.environ.get("AWS_REGION", "us-east-1"),
                "allowed_origins": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_ALLOWED_ORIGINS", "*").split(","),
                "publish_exports": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_PUBLISH_EXPORTS", "false").lower()
                in {"1", "true", "yes", "on"},
                "publish_tiles": os.environ.get("UK_WSR_VISUALIZER_OBJECT_STORE_PUBLISH_TILES", "true").lower()
                in {"1", "true", "yes", "on"},
                "publish_validation_reports": os.environ.get(
                    "UK_WSR_VISUALIZER_OBJECT_STORE_PUBLISH_VALIDATION_REPORTS", "true"
                ).lower()
                in {"1", "true", "yes", "on"},
                "dataset_title": os.environ.get("UK_WSR_VISUALIZER_DATASET_TITLE", "UK WSR aggregate HDF5"),
                "dataset_description": os.environ.get(
                    "UK_WSR_VISUALIZER_DATASET_DESCRIPTION",
                    "Daily ODIM-like aggregate HDF5 files produced by the UK WSR pipeline, "
                    "with derived preview and export products generated by the UK WSR Visualizer.",
                ),
                "dataset_license": os.environ.get("UK_WSR_VISUALIZER_DATASET_LICENSE", "proprietary"),
                "dataset_citation": os.environ.get("UK_WSR_VISUALIZER_DATASET_CITATION", ""),
                "dataset_provider_name": os.environ.get("UK_WSR_VISUALIZER_DATASET_PROVIDER_NAME", "NCAS Radar Science Group"),
                "dataset_provider_url": os.environ.get("UK_WSR_VISUALIZER_DATASET_PROVIDER_URL", ""),
                "dataset_contact_email": os.environ.get("UK_WSR_VISUALIZER_DATASET_CONTACT_EMAIL", ""),
                "dataset_terms_url": os.environ.get("UK_WSR_VISUALIZER_DATASET_TERMS_URL", ""),
            }
        )

    def public_metadata(self) -> dict[str, str]:
        return {
            "title": self.dataset_title,
            "description": self.dataset_description,
            "license": self.dataset_license,
            "citation": self.dataset_citation,
            "provider_name": self.dataset_provider_name,
            "provider_url": self.dataset_provider_url,
            "contact_email": self.dataset_contact_email,
            "terms_url": self.dataset_terms_url,
        }


def load_object_store_config(path: Path | None) -> ObjectStoreConfig:
    if path is None:
        return ObjectStoreConfig.from_env()
    return ObjectStoreConfig.from_file(path)


def cors_xml(config: ObjectStoreConfig) -> str:
    origins = "\n".join(f"    <AllowedOrigin>{origin}</AllowedOrigin>" for origin in config.allowed_origins)
    return (
        "<CORSConfiguration>\n"
        "  <CORSRule>\n"
        f"{origins}\n"
        "    <AllowedMethod>GET</AllowedMethod>\n"
        "    <AllowedMethod>HEAD</AllowedMethod>\n"
        "    <AllowedHeader>*</AllowedHeader>\n"
        "  </CORSRule>\n"
        "</CORSConfiguration>\n"
    )
