"""STAC JSON helpers for public Avocet UK radar catalog publication."""

from __future__ import annotations

from dataclasses import asdict

from .catalog import CatalogItem
from .object_store import (
    aggregate_object_key,
    checksum_object_key,
    join_object_url,
    preview_object_prefix,
    stac_catalog_object_key,
    stac_collection_object_key,
    stac_object_key,
    tile_object_prefix,
)

STAC_VERSION = "1.0.0"
AGGREGATE_COLLECTION_ID = "avocet-uk-radar-aggregate-h5"

DEFAULT_PUBLIC_METADATA = {
    "title": "Avocet UK radar aggregate HDF5",
    "description": (
        "Daily ODIM-like aggregate HDF5 files produced by the Avocet UK radar pipeline, "
        "with derived preview and export products generated by the Avocet Radar Toolkit."
    ),
    "license": "proprietary",
    "citation": "",
    "provider_name": "NCAS Radar Science Group",
    "provider_url": "",
    "contact_email": "",
    "terms_url": "",
}


def _metadata(overrides: dict[str, str] | None = None) -> dict[str, str]:
    metadata = dict(DEFAULT_PUBLIC_METADATA)
    if overrides:
        metadata.update({key: str(value) for key, value in overrides.items() if value is not None})
    return metadata


def _metadata_links(metadata: dict[str, str]) -> list[dict[str, object]]:
    links: list[dict[str, object]] = []
    if metadata.get("terms_url"):
        links.append(
            {
                "rel": "license",
                "href": metadata["terms_url"],
                "type": "text/html",
                "title": "Dataset terms and licence",
            }
        )
    if metadata.get("provider_url"):
        links.append(
            {
                "rel": "about",
                "href": metadata["provider_url"],
                "type": "text/html",
                "title": metadata.get("provider_name") or "Provider",
            }
        )
    return links


def _date_time(date: str) -> str:
    return f"{date[:4]}-{date[4:6]}-{date[6:8]}T00:00:00Z"


def _item_spatial(item: CatalogItem) -> tuple[dict[str, object], list[float] | None, dict[str, object] | None]:
    spatial = item.root_attrs.get("avocet:spatial", {}) if isinstance(item.root_attrs, dict) else {}
    bbox = spatial.get("bbox") if isinstance(spatial, dict) and isinstance(spatial.get("bbox"), list) else None
    lon = spatial.get("longitude") if isinstance(spatial, dict) else None
    lat = spatial.get("latitude") if isinstance(spatial, dict) else None
    geometry = {"type": "Point", "coordinates": [lon, lat]} if lon is not None and lat is not None else None
    return spatial if isinstance(spatial, dict) else {}, bbox, geometry


def _collection_extent(items: list[CatalogItem]) -> dict[str, object]:
    bboxes = []
    dates = []
    for item in items:
        _spatial, bbox, _geometry = _item_spatial(item)
        if bbox and len(bbox) == 4:
            bboxes.append([float(value) for value in bbox])
        dates.append(item.date)

    if bboxes:
        spatial_bbox = [
            min(bbox[0] for bbox in bboxes),
            min(bbox[1] for bbox in bboxes),
            max(bbox[2] for bbox in bboxes),
            max(bbox[3] for bbox in bboxes),
        ]
    else:
        spatial_bbox = [-180.0, -90.0, 180.0, 90.0]

    temporal_interval = [_date_time(min(dates)) if dates else None, _date_time(max(dates)) if dates else None]
    return {
        "spatial": {"bbox": [spatial_bbox]},
        "temporal": {"interval": [temporal_interval]},
    }


def item_to_stac(
    item: CatalogItem,
    public_base_url: str = "",
    object_prefix: str = "uk-radar",
    include_links: bool = True,
    public_metadata: dict[str, str] | None = None,
) -> dict[str, object]:
    metadata = _metadata(public_metadata)
    spatial, bbox, geometry = _item_spatial(item)
    aggregate_href = item.object_url or item.path
    checksum_href = ""
    preview_href = ""
    tiles_href = ""
    if public_base_url:
        aggregate_href = join_object_url(public_base_url, aggregate_object_key(item.radar, item.date, object_prefix))
        checksum_href = join_object_url(public_base_url, checksum_object_key(item.date[:4], item.radar, object_prefix))
        preview_href = join_object_url(public_base_url, preview_object_prefix(item.radar, item.date, object_prefix))
        pulse_for_tiles = item.pulses[0] if item.pulses else "{pulse}"
        quantity_for_tiles = item.quantities[0] if item.quantities else "{quantity}"
        tiles_href = join_object_url(
            public_base_url,
            tile_object_prefix(item.radar, item.date, pulse_for_tiles, quantity_for_tiles, object_prefix),
        )
    links: list[dict[str, object]] = []
    if include_links:
        links = [
            {
                "rel": "collection",
                "href": join_object_url(public_base_url, stac_collection_object_key(AGGREGATE_COLLECTION_ID, object_prefix))
                if public_base_url
                else "collection.json",
                "type": "application/json",
            },
            {
                "rel": "self",
                "href": join_object_url(public_base_url, stac_object_key(AGGREGATE_COLLECTION_ID, item.item_id, object_prefix))
                if public_base_url
                else f"{item.item_id}.json",
                "type": "application/json",
            },
        ]
    return {
        "type": "Feature",
        "stac_version": STAC_VERSION,
        "id": item.item_id,
        "collection": AGGREGATE_COLLECTION_ID,
        "geometry": geometry,
        "bbox": bbox,
        "properties": {
            "datetime": _date_time(item.date),
            "radar": item.radar,
            "radar_num": item.radar_num,
            "pulses": item.pulses,
            "times": item.times,
            "quantities": item.quantities,
            "validation_status": item.validation_status,
            "license": metadata["license"],
            "sci:citation": metadata["citation"],
            "avocet:provider": metadata["provider_name"],
            "avocet:contact_email": metadata["contact_email"],
            "avocet:spatial": spatial,
        },
        "assets": {
            "aggregate_h5": {
                "href": aggregate_href,
                "type": "application/x-hdf5",
                "roles": ["data"],
                "title": "Avocet aggregate HDF5",
            },
            "metadata": {
                "href": aggregate_href,
                "roles": ["metadata"],
                "title": "Catalog item metadata",
            },
            "sha256_manifest": {
                "href": checksum_href or f"../../checksums/sha256/{item.date[:4]}/{item.radar}.json",
                "type": "application/json",
                "roles": ["metadata", "checksum"],
                "title": "SHA256 checksum manifest for this radar/year",
            },
            "preview_prefix": {
                "href": preview_href or f"../../previews/radar={item.radar}/date={item.date}/",
                "type": "application/json",
                "roles": ["overview", "derived"],
                "title": "Published preview prefix",
            },
            "tile_prefix": {
                "href": tiles_href or f"../../tiles/radar={item.radar}/date={item.date}/",
                "type": "application/json",
                "roles": ["tiles", "derived"],
                "title": "Published tile prefix",
            },
            "validation_prefix": {
                "href": join_object_url(public_base_url, f"{object_prefix}/validation/wct")
                if public_base_url
                else "../../validation/wct/",
                "type": "application/json",
                "roles": ["metadata", "quality"],
                "title": "WCT parity validation report prefix",
            },
            "derived_geotiff_template": {
                "href": "{exports}/geotiff",
                "type": "image/tiff; application=geotiff",
                "roles": ["derived", "data"],
                "title": "GeoTIFF export generated by API/CLI",
            },
            "derived_cf_netcdf_template": {
                "href": "{exports}/cf_netcdf",
                "type": "application/netcdf",
                "roles": ["derived", "data"],
                "title": "CF NetCDF export generated by API/CLI",
            },
            "derived_contours_template": {
                "href": "{exports}/geojson",
                "type": "application/geo+json",
                "roles": ["derived", "metadata"],
                "title": "Contour vector export generated by API/CLI",
            },
        },
        "links": links,
        "avocet:quantity_records": [asdict(record) for record in item.quantity_records],
    }


def collection_to_stac(
    items: list[CatalogItem],
    public_base_url: str = "",
    object_prefix: str = "uk-radar",
    include_item_links: bool = True,
    public_metadata: dict[str, str] | None = None,
) -> dict[str, object]:
    metadata = _metadata(public_metadata)
    links: list[dict[str, object]] = [
        {
            "rel": "root",
            "href": join_object_url(public_base_url, stac_catalog_object_key(object_prefix)) if public_base_url else "../catalog.json",
            "type": "application/json",
        },
        {
            "rel": "self",
            "href": join_object_url(public_base_url, stac_collection_object_key(AGGREGATE_COLLECTION_ID, object_prefix))
            if public_base_url
            else "collection.json",
            "type": "application/json",
        },
    ]
    links.extend(_metadata_links(metadata))
    if include_item_links:
        links.extend(
            {
                "rel": "item",
                "href": join_object_url(public_base_url, stac_object_key(AGGREGATE_COLLECTION_ID, item.item_id, object_prefix))
                if public_base_url
                else f"{item.item_id}.json",
                "type": "application/geo+json",
                "title": item.item_id,
            }
            for item in items
        )
    return {
        "type": "Collection",
        "stac_version": STAC_VERSION,
        "id": AGGREGATE_COLLECTION_ID,
        "title": metadata["title"],
        "description": metadata["description"],
        "license": metadata["license"],
        "providers": [
            {
                "name": metadata["provider_name"],
                "roles": ["producer", "processor", "host"],
                **({"url": metadata["provider_url"]} if metadata.get("provider_url") else {}),
            }
        ],
        "extent": _collection_extent(items),
        "summaries": {
            "radar": sorted({item.radar for item in items}),
            "radar_num": sorted({item.radar_num for item in items}),
            "pulses": sorted({pulse for item in items for pulse in item.pulses}),
            "quantities": sorted({quantity for item in items for quantity in item.quantities}),
        },
        "links": links,
        "sci:citation": metadata["citation"],
        "avocet:contact_email": metadata["contact_email"],
        "avocet:terms_url": metadata["terms_url"],
    }


def root_catalog_to_stac(
    items: list[CatalogItem],
    public_base_url: str = "",
    object_prefix: str = "uk-radar",
    public_metadata: dict[str, str] | None = None,
) -> dict[str, object]:
    metadata = _metadata(public_metadata)
    collection_href = (
        join_object_url(public_base_url, stac_collection_object_key(AGGREGATE_COLLECTION_ID, object_prefix))
        if public_base_url
        else f"{AGGREGATE_COLLECTION_ID}/collection.json"
    )
    return {
        "type": "Catalog",
        "stac_version": STAC_VERSION,
        "id": "avocet-uk-radar",
        "title": metadata["title"],
        "description": metadata["description"],
        "links": [
            {
                "rel": "self",
                "href": join_object_url(public_base_url, stac_catalog_object_key(object_prefix))
                if public_base_url
                else "catalog.json",
                "type": "application/json",
            },
            {
                "rel": "child",
                "href": collection_href,
                "type": "application/json",
                "title": "Avocet UK radar aggregate HDF5",
            },
        ]
        + _metadata_links(metadata),
        "avocet:item_count": len(items),
        "sci:citation": metadata["citation"],
        "avocet:contact_email": metadata["contact_email"],
    }
