from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class StaticViewerTests(unittest.TestCase):
    def test_viewer_has_wct_style_layer_controls(self):
        html = (ROOT / "src/avocet_radar_toolkit/static/index.html").read_text(encoding="utf-8")
        self.assertIn('id="paletteSelect"', html)
        self.assertIn('id="customPaletteInput"', html)
        self.assertIn('id="basemapSelect"', html)
        self.assertIn('id="minRangeInput"', html)
        self.assertIn('id="maxAzimuthInput"', html)
        self.assertIn('id="minValueInput"', html)
        self.assertIn('id="cappiHeightInput"', html)
        self.assertIn('id="downloadProjectButton"', html)
        self.assertIn('id="projectFileInput"', html)
        self.assertIn('id="objectUrlButton"', html)
        self.assertIn('id="openObjectButton"', html)
        self.assertIn('id="clearRawCacheButton"', html)
        self.assertIn('id="timePrevButton"', html)
        self.assertIn('id="timeNextButton"', html)
        self.assertIn('id="timeStepOutput"', html)
        self.assertIn('class="crosshair"', html)
        self.assertIn('class="tile-layer"', html)
        self.assertIn('class="ppi-canvas"', html)
        self.assertIn('class="map-overlay-canvas"', html)
        self.assertIn('class="colour-legend"', html)
        self.assertIn('value="osm"', html)
        self.assertIn('value="auto"', html)
        self.assertIn('value="homeyer"', html)
        self.assertNotIn('id="mathButton"', html)
        self.assertNotIn('id="tileButton"', html)
        self.assertNotIn('id="exportButton"', html)
        self.assertNotIn('id="contourButton"', html)
        self.assertNotIn('id="hydrateItemButton"', html)

    def test_viewer_wires_preview_metadata_and_identify_endpoints(self):
        js = (ROOT / "src/avocet_radar_toolkit/static/app.js").read_text(encoding="utf-8")
        self.assertIn("/api/ppi/", js)
        self.assertIn("/api/identify/", js)
        self.assertIn("panelMeta", js)
        self.assertIn("setBasemap", js)
        self.assertIn("schedulePreview", js)
        self.assertIn("updateTimeStepOutput", js)
        self.assertIn("availableTimesForSelection", js)
        self.assertIn("uniqueSorted", js)
        self.assertIn("quantity_records", js)
        self.assertIn("setPanelMessage", js)
        self.assertIn("Catalog loaded:", js)
        self.assertIn("Catalog search returned no data", js)
        self.assertIn("timeSelect\").disabled = times.length === 0", js)
        self.assertIn("timePrevButton", js)
        self.assertIn("timeNextButton", js)
        self.assertIn("applyOpacity", js)
        self.assertIn("previewRequestSeq", js)
        self.assertIn("renderPpi", js)
        self.assertIn("renderPpiGateMesh", js)
        self.assertIn("gate_edges", js)
        self.assertIn("polygonIntersectsCanvas", js)
        self.assertIn("STANDARD_PALETTES", js)
        self.assertIn("homeyer", js)
        self.assertIn("renderTiles", js)
        self.assertIn("renderLegend", js)
        self.assertIn("legendGradient", js)
        self.assertIn("quantityUnit", js)
        self.assertIn("OpenStreetMap", html := (ROOT / "src/avocet_radar_toolkit/static/index.html").read_text(encoding="utf-8"))
        self.assertIn("paletteSelect", js)
        self.assertIn("palette_stops", js)
        self.assertIn("range_km", js)
        self.assertIn("azimuth_deg", js)
        self.assertIn("latitude", js)
        self.assertIn("longitude", js)
        self.assertIn("filterParams", js)
        self.assertIn("min_range_km", js)
        self.assertIn("max_azimuth_deg", js)
        self.assertIn("cappi_height_m", js)
        self.assertNotIn("/api/math", js)
        self.assertNotIn("createMathProduct", js)
        self.assertNotIn("/api/tiles", js)
        self.assertNotIn("createTileProduct", js)
        self.assertNotIn("/api/contours/", js)
        self.assertIn("remote object-store catalog", js)
        self.assertIn("openObjectUrl", js)
        self.assertIn("clearRawCache", js)
        self.assertIn("/api/cache/raw/clear", js)
        self.assertNotIn("/hydrate", js)
        self.assertIn("currentSessionState", js)
        self.assertIn("customPalette", js)
        self.assertIn("downloadProject", js)
        self.assertIn("importProjectFile", js)
        self.assertIn("avocet-wct-project", js)

    def test_viewer_places_activity_and_colourbar_at_top(self):
        css = (ROOT / "src/avocet_radar_toolkit/static/styles.css").read_text(encoding="utf-8")
        self.assertIn(".identify-readout", css)
        self.assertIn("top: 44px", css)
        self.assertIn(".colour-legend", css)
        self.assertIn("top: 10px", css)
        self.assertIn("grid-template-rows: auto 180px", css)
        self.assertIn("width: 28px", css)


if __name__ == "__main__":
    unittest.main()
