from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class StaticViewerTests(unittest.TestCase):
    def test_viewer_has_radar_layer_controls(self):
        html = (ROOT / "src/uk_wsr_visualizer/static/index.html").read_text(encoding="utf-8")
        self.assertIn('id="paletteSelect"', html)
        self.assertIn('id="customPaletteInput"', html)
        self.assertIn('id="basemapSelect"', html)
        self.assertIn('id="minRangeInput"', html)
        self.assertIn('id="maxAzimuthInput"', html)
        self.assertIn('id="displayMinInput"', html)
        self.assertIn('id="displayMaxInput"', html)
        self.assertIn('id="rangeRingsInput"', html)
        self.assertIn('id="rangeRingSpacingInput"', html)
        self.assertIn('id="linkViewInput"', html)
        self.assertIn('id="linkTimeInput"', html)
        self.assertIn('id="linkVariableInput"', html)
        self.assertIn('id="linkElevationInput"', html)
        self.assertIn('id="minValueInput"', html)
        self.assertIn('id="cappiHeightInput"', html)
        self.assertIn('id="noiseFloorInput" type="checkbox" checked', html)
        self.assertIn("Learned cleanup: persistent background and static clutter", html)
        self.assertIn("Advanced diagnostics and filters", html)
        self.assertIn('id="noiseFloorMarginInput" type="number" step="0.5" value="0"', html)
        self.assertIn('id="downloadProjectButton"', html)
        self.assertIn('id="projectFileInput"', html)
        self.assertIn('id="objectUrlButton"', html)
        self.assertIn('id="openObjectButton"', html)
        self.assertIn('id="clearRawCacheButton"', html)
        self.assertIn('id="performanceButton"', html)
        self.assertIn('id="performanceDialog"', html)
        self.assertIn('id="downloadPerformanceButton"', html)
        self.assertIn('id="timePrevButton"', html)
        self.assertIn('id="timeNextButton"', html)
        self.assertIn('id="timeStepOutput"', html)
        self.assertIn('id="exportFormatSelect"', html)
        self.assertIn('id="createExportButton"', html)
        self.assertIn('id="viewManifestButton"', html)
        self.assertIn('id="downloadExportButton"', html)
        self.assertIn('id="exportStatus"', html)
        self.assertIn('id="exportLinks"', html)
        self.assertIn('id="recentSelections"', html)
        self.assertIn('id="clearRecentButton"', html)
        self.assertIn('value="screenshot_png"', html)
        self.assertIn("Screenshot: as displayed", html)
        self.assertIn("Polar PPI PNG", html)
        self.assertIn("Georeferenced map overlay", html)
        self.assertIn("Georeferenced GeoTIFF", html)
        self.assertIn('value="mp4"', html)
        self.assertIn('placeholder="YYYY-MM-DD"', html)
        self.assertIn('pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}"', html)
        self.assertNotIn('type="date"', html)
        self.assertIn('class="crosshair"', html)
        self.assertIn('class="tile-layer"', html)
        self.assertIn('class="ppi-canvas"', html)
        self.assertIn('class="map-overlay-canvas"', html)
        self.assertIn('class="colour-legend"', html)
        self.assertIn('class="pointer-field-toggle"', html)
        self.assertIn('class="panel-time-select"', html)
        self.assertIn('id="fitViewButton"', html)
        self.assertIn('value="height" checked', html)
        self.assertIn('value="bin"', html)
        self.assertIn('value="osm"', html)
        self.assertIn('value="auto"', html)
        self.assertIn('value="homeyer"', html)
        self.assertNotIn('id="mathButton"', html)
        self.assertNotIn('id="tileButton"', html)
        self.assertNotIn('id="exportButton"', html)
        self.assertNotIn('id="contourButton"', html)
        self.assertNotIn('id="hydrateItemButton"', html)

    def test_viewer_wires_preview_metadata_and_identify_endpoints(self):
        js = (ROOT / "src/uk_wsr_visualizer/static/app.js").read_text(encoding="utf-8")
        self.assertIn("/api/ppi/", js)
        self.assertIn("/api/identify/", js)
        self.assertIn("panelMeta", js)
        self.assertIn("setBasemap", js)
        self.assertIn("schedulePreview", js)
        self.assertIn('if (el("noiseFloorInput").checked || backgroundModelPath)', js)
        self.assertIn("params.qc_background_model_enabled = true", js)
        self.assertIn("updateTimeStepOutput", js)
        self.assertIn("availableTimesForSelection", js)
        self.assertIn("uniqueSorted", js)
        self.assertIn("quantity_records", js)
        self.assertIn("isPlotVariableQuantity", js)
        self.assertIn('!upper.includes("NOISE")', js)
        self.assertIn("setPanelMessage", js)
        self.assertIn("hydrateItemDetails", js)
        self.assertIn("/hydrate", js)
        self.assertIn("Looking for its raw-volume time and field index", js)
        self.assertIn("rawVolumeKeySet", js)
        self.assertIn("raw-volume days found", js)
        self.assertIn("formatDate", js)
        self.assertIn("Catalog loaded:", js)
        self.assertIn("No catalog data for", js)
        self.assertIn("timeSelect\").disabled = times.length === 0", js)
        self.assertIn("timePrevButton", js)
        self.assertIn("timeNextButton", js)
        self.assertIn("applyOpacity", js)
        self.assertIn("previewRequestSeq", js)
        self.assertIn("ppiFrameCache", js)
        self.assertIn("rawCacheByItem", js)
        self.assertIn("/api/raw-cache/day/", js)
        self.assertIn("/api/raw-cache/prefetch/", js)
        self.assertIn("/api/performance", js)
        self.assertIn("downloadPerformanceReport", js)
        self.assertIn("pushPerformanceEvent", js)
        self.assertIn("server_elapsed_ms", js)
        self.assertIn("prefetchRawFile", js)
        self.assertIn("prefetchAdjacentFrames", js)
        self.assertIn("Loading next frame", js)
        self.assertIn("Keeping previous frame visible", js)
        self.assertIn("renderPanel(panel, ppi, {preserveView", js)
        self.assertIn("renderPpi", js)
        self.assertIn("renderPpiGateMesh", js)
        self.assertIn("gate_edges", js)
        self.assertIn("polygonIntersectsCanvas", js)
        self.assertIn("STANDARD_PALETTES", js)
        self.assertIn("homeyer", js)
        self.assertIn("renderTiles", js)
        self.assertIn("renderLegend", js)
        self.assertIn("legendGradient", js)
        self.assertIn("quantityUnit", js)
        self.assertIn("OpenStreetMap", html := (ROOT / "src/uk_wsr_visualizer/static/index.html").read_text(encoding="utf-8"))
        self.assertIn("paletteSelect", js)
        self.assertIn("palette_stops", js)
        self.assertIn("range_km", js)
        self.assertIn("azimuth_deg", js)
        self.assertIn("latitude", js)
        self.assertIn("longitude", js)
        self.assertIn("pointerFields", js)
        self.assertIn("beamHeightM", js)
        self.assertIn("height=", js)
        self.assertIn("display_min", js)
        self.assertIn("rangeRingSpacingInput", js)
        self.assertIn("syncLinkedViewFromPanel", js)
        self.assertIn("handleKeyboardNavigation", js)
        self.assertIn("stepElevation", js)
        self.assertIn("comparisonLinks", js)
        self.assertIn("linkTimeInput", js)
        self.assertIn("panel-time-select", js)
        self.assertIn("loadVisiblePpisNow", js)
        self.assertIn("updateExportLinks", js)
        self.assertIn("filterParams", js)
        self.assertIn("min_range_km", js)
        self.assertIn("max_azimuth_deg", js)
        self.assertIn("cappi_height_m", js)
        self.assertIn("const DEFAULT_CLEANUP_ENABLED = true", js)
        self.assertIn("const DEFAULT_CLEANUP_MARGIN_DB = 0", js)
        self.assertIn('const DEFAULT_QC_MODE = "signal_preserving"', js)
        self.assertIn("params.noise_floor_window_bins = 11", js)
        self.assertIn("params.qc_mode = DEFAULT_QC_MODE", js)
        self.assertIn("params.qc_static_clutter_enabled = true", js)
        self.assertIn("params.qc_background_model_enabled = true", js)
        self.assertNotIn("params.qc_companion_enabled = true", js)
        self.assertNotIn("params.noise_floor_texture_enabled = true", js)
        self.assertNotIn("/api/math", js)
        self.assertNotIn("createMathProduct", js)
        self.assertNotIn("/api/tiles", js)
        self.assertNotIn("createTileProduct", js)
        self.assertNotIn("/api/contours/", js)
        self.assertIn("remote object-store catalog", js)
        self.assertIn("openObjectUrl", js)
        self.assertIn("clearRawCache", js)
        self.assertIn("/api/cache/raw/clear", js)
        self.assertIn("currentSessionState", js)
        self.assertIn("customPalette", js)
        self.assertIn("downloadProject", js)
        self.assertIn("importProjectFile", js)
        self.assertIn("uk-wsr-visualizer-project", js)
        self.assertIn("coordinateModeForExport", js)
        self.assertIn("screen_view", js)
        self.assertIn("polar_ppi", js)
        self.assertIn("georeferenced_map_overlay", js)
        self.assertIn("/api/export", js)
        self.assertIn("/manifest", js)
        self.assertIn("currentPrimaryExportSelection", js)
        self.assertIn("Create a completed export", js)
        self.assertIn("/api/recent-selections", js)
        self.assertIn("recordRecentSelection", js)
        self.assertIn("restoreRecentSelection", js)
        self.assertIn("clearRecentSelections", js)
        self.assertIn("request.times", js)
        self.assertIn("frame_delay_ms", js)
        self.assertIn("touchstart", js)
        self.assertIn("touchmove", js)
        self.assertIn("touchDistance", js)
        self.assertIn("zoomPanelAt", js)
        self.assertIn("panPanel", js)

    def test_viewer_places_activity_and_colourbar_at_top(self):
        css = (ROOT / "src/uk_wsr_visualizer/static/styles.css").read_text(encoding="utf-8")
        self.assertIn(".identify-readout", css)
        self.assertIn("top: 44px", css)
        self.assertIn(".colour-legend", css)
        self.assertIn("top: 10px", css)
        self.assertIn("grid-template-rows: auto 180px", css)
        self.assertIn("width: 28px", css)


if __name__ == "__main__":
    unittest.main()
