from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class StaticViewerTests(unittest.TestCase):
    def test_viewer_has_radar_layer_controls(self):
        html = (ROOT / "src/uk_wsr_visualizer/static/index.html").read_text(encoding="utf-8")
        self.assertIn('id="paletteSelect"', html)
        self.assertIn('id="customPaletteInput"', html)
        self.assertIn('id="basemapSelect"', html)
        self.assertIn('id="minRangeInput"', html)
        self.assertIn('id="maxAzimuthInput"', html)
        self.assertIn('id="displayMinInput"', html)
        self.assertIn('id="displayMaxInput"', html)
        self.assertIn('id="rangeRingsInput"', html)
        self.assertIn('id="rangeRingSpacingInput"', html)
        self.assertIn('id="nearestRadarButton"', html)
        self.assertIn('id="siteOverlayInput"', html)
        self.assertIn('id="linkViewInput"', html)
        self.assertIn('id="linkVariableInput"', html)
        self.assertIn('id="linkElevationInput"', html)
        self.assertIn('id="minValueInput"', html)
        self.assertIn('id="cappiHeightInput"', html)
        self.assertIn('id="downloadProjectButton"', html)
        self.assertIn('id="projectFileInput"', html)
        self.assertIn('id="objectUrlButton"', html)
        self.assertIn('id="openObjectButton"', html)
        self.assertIn('id="clearRawCacheButton"', html)
        self.assertIn('id="timePrevButton"', html)
        self.assertIn('id="timeNextButton"', html)
        self.assertIn('id="timeStepOutput"', html)
        self.assertIn('id="exportFormatSelect"', html)
        self.assertIn('id="createExportButton"', html)
        self.assertIn('id="viewManifestButton"', html)
        self.assertIn('id="downloadExportButton"', html)
        self.assertIn('id="exportStatus"', html)
        self.assertIn('id="preVpEnabledInput"', html)
        self.assertIn('id="preVpPresetSelect"', html)
        self.assertIn('value="current_ci_le4" selected', html)
        self.assertIn('value="aggressive_ci_le4"', html)
        self.assertIn('id="preVpAdvancedControls"', html)
        self.assertIn('id="preVpPreviewButton"', html)
        self.assertIn('id="preVpDiagnostics"', html)
        self.assertIn('id="preVpPreviewDialog"', html)
        self.assertIn('id="diagnosticsButton"', html)
        self.assertIn('id="diagnosticsDialog"', html)
        self.assertIn('id="diagnosticVariablesInput"', html)
        self.assertIn('id="fourElevationPresetButton"', html)
        self.assertIn('id="fourVariablePresetButton"', html)
        self.assertIn('id="fitSweepButton"', html)
        self.assertIn('id="copyReadoutButton"', html)
        self.assertIn('id="pinReadoutButton"', html)
        self.assertIn('id="clearPinsButton"', html)
        self.assertIn('id="pinnedReadouts"', html)
        self.assertIn('placeholder="YYYY-MM-DD"', html)
        self.assertIn('pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}"', html)
        self.assertNotIn('type="date"', html)
        self.assertIn('class="crosshair"', html)
        self.assertIn('class="tile-layer"', html)
        self.assertIn('class="ppi-canvas"', html)
        self.assertIn('class="map-overlay-canvas"', html)
        self.assertIn('class="colour-legend"', html)
        self.assertIn('class="pointer-field-toggle"', html)
        self.assertIn('value="height" checked', html)
        self.assertIn('value="bin"', html)
        self.assertIn('value="osm"', html)
        self.assertIn('value="auto"', html)
        self.assertIn('value="homeyer"', html)
        self.assertNotIn('id="mathButton"', html)
        self.assertNotIn('id="tileButton"', html)
        self.assertNotIn('id="exportButton"', html)
        self.assertNotIn('id="contourButton"', html)
        self.assertNotIn('id="hydrateItemButton"', html)

    def test_viewer_wires_preview_metadata_and_identify_endpoints(self):
        js = (ROOT / "src/uk_wsr_visualizer/static/app.js").read_text(encoding="utf-8")
        self.assertIn("/api/ppi/", js)
        self.assertIn("/api/identify/", js)
        self.assertIn("panelMeta", js)
        self.assertIn("setBasemap", js)
        self.assertIn("schedulePreview", js)
        self.assertIn("updateTimeStepOutput", js)
        self.assertIn("availableTimesForSelection", js)
        self.assertIn("uniqueSorted", js)
        self.assertIn("quantity_records", js)
        self.assertIn("setPanelMessage", js)
        self.assertIn("hydrateItemDetails", js)
        self.assertIn("/hydrate", js)
        self.assertIn("Looking for its raw-volume time and field index", js)
        self.assertIn("rawVolumeKeySet", js)
        self.assertIn("raw-volume days found", js)
        self.assertIn("formatDate", js)
        self.assertIn("Catalog loaded:", js)
        self.assertIn("No catalog data for", js)
        self.assertIn("timeSelect\").disabled = times.length === 0", js)
        self.assertIn("timePrevButton", js)
        self.assertIn("timeNextButton", js)
        self.assertIn("applyOpacity", js)
        self.assertIn("previewRequestSeq", js)
        self.assertIn("renderPpi", js)
        self.assertIn("renderPpiGateMesh", js)
        self.assertIn("gate_edges", js)
        self.assertIn("polygonIntersectsCanvas", js)
        self.assertIn("STANDARD_PALETTES", js)
        self.assertIn("homeyer", js)
        self.assertIn("renderTiles", js)
        self.assertIn("renderLegend", js)
        self.assertIn("legendGradient", js)
        self.assertIn("quantityUnit", js)
        self.assertIn("OpenStreetMap", html := (ROOT / "src/uk_wsr_visualizer/static/index.html").read_text(encoding="utf-8"))
        self.assertIn("paletteSelect", js)
        self.assertIn("palette_stops", js)
        self.assertIn("range_km", js)
        self.assertIn("azimuth_deg", js)
        self.assertIn("latitude", js)
        self.assertIn("longitude", js)
        self.assertIn("pointerFields", js)
        self.assertIn("beamHeightM", js)
        self.assertIn("height=", js)
        self.assertIn("display_min", js)
        self.assertIn("rangeRingSpacingInput", js)
        self.assertIn("navigator.geolocation", js)
        self.assertIn("chooseNearestAvailableRadar", js)
        self.assertIn("spatialForRadarSlug", js)
        self.assertIn("renderSiteOverlay", js)
        self.assertIn("distanceKm", js)
        self.assertIn("syncLinkedViewFromPanel", js)
        self.assertIn("handleKeyboardNavigation", js)
        self.assertIn("stepElevation", js)
        self.assertIn("comparisonLinks", js)
        self.assertIn("filterParams", js)
        self.assertIn("min_range_km", js)
        self.assertIn("max_azimuth_deg", js)
        self.assertIn("cappi_height_m", js)
        self.assertNotIn("/api/math", js)
        self.assertNotIn("createMathProduct", js)
        self.assertNotIn("/api/tiles", js)
        self.assertNotIn("createTileProduct", js)
        self.assertNotIn("/api/contours/", js)
        self.assertIn("remote object-store catalog", js)
        self.assertIn("openObjectUrl", js)
        self.assertIn("clearRawCache", js)
        self.assertIn("/api/cache/raw/clear", js)
        self.assertIn("/api/pre-vp-filter/presets", js)
        self.assertIn("/api/pre-vp-preview/", js)
        self.assertIn("preVpQuerySettings", js)
        self.assertIn("showPreVpPreview", js)
        self.assertIn("preVpFiltering", js)
        self.assertIn("Validation found this setting too destructive", html)
        self.assertIn("isPlotReadyQuantity", js)
        self.assertIn("isDiagnosticQuantity", js)
        self.assertIn("Show calibration/diagnostic variables", html)
        self.assertIn("Calibration and diagnostics", js)
        self.assertIn("Metadata noise profile", html)
        self.assertIn("showDiagnostics", js)
        self.assertIn("/api/diagnostics", js)
        self.assertIn("applyFourElevationPreset", js)
        self.assertIn("applyFourVariablePreset", js)
        self.assertIn("copyLastReadout", js)
        self.assertIn("pinLastReadout", js)
        self.assertIn("pinnedReadouts", js)
        self.assertIn("currentSessionState", js)
        self.assertIn("customPalette", js)
        self.assertIn("downloadProject", js)
        self.assertIn("importProjectFile", js)
        self.assertIn("uk-wsr-visualizer-project", js)
        self.assertIn("/api/export", js)
        self.assertIn("/manifest", js)
        self.assertIn("currentPrimaryExportSelection", js)
        self.assertIn("Create a completed export", js)

    def test_viewer_places_activity_and_colourbar_at_top(self):
        css = (ROOT / "src/uk_wsr_visualizer/static/styles.css").read_text(encoding="utf-8")
        self.assertIn(".identify-readout", css)
        self.assertIn("top: 44px", css)
        self.assertIn(".colour-legend", css)
        self.assertIn("top: 10px", css)
        self.assertIn("grid-template-rows: auto 180px", css)
        self.assertIn("width: 28px", css)


if __name__ == "__main__":
    unittest.main()
